import Head from "next/head";
import Image from "next/image";
import { Sidebar, Mainbar, Topbar } from "./../components/editor";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="  tw-bg-black tw-overflow-hidden">
        <div className="tw-flex tw-w-screen tw-h-screen  tw-flex-row ">
          <div className="">
            <Sidebar />
          </div>
          <div className="tw-flex tw-flex-col  tw-w-full">
            <div className="">
              <Topbar />
            </div>
            <div className=" tw-w-full tw-overflow-y-scroll tw-h-full">
              <Mainbar />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
